name: 'AppSecAI'

runs:
  using: 'composite'
  steps:
    - name: 'Install Python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 'Install AppSec'
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        pip install .

    - name: 'Run AppSec'
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        cli_opts=" --repo ${GITHUB_REPOSITORY}"
        cli_opts+=" --to ${{ github.event.number }}"
        python -m appsec $cli_opts
