name: 'AppSecAI'

inputs:
  autograd_token:
    type: string
    required: true
    description: 'Autograd token to create runs'

runs:
  using: 'composite'
  steps:
    - name: 'Install Python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 'Install AppSec'
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        pip install .

    - name: 'Run AppSec'
      shell: bash
      env:
        AUTOGRAD_API_TOKEN: ${{ inputs.autograd_token }}
      run: |
        cli_opts=" --repo ${{ github.repository }}"
        cli_opts+=" --to_event ${{ github.event.number }}"
        python -m appsec $cli_opts
